packages:
  - "packages/*"

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - "@moon7/*"

registries:
  default: https://registry.npmjs.org/
  "@moon7": https://registry.npmjs.org/

versioning:
  changelog:
    storage: repository
  ignore:
    - "@moon7/internal-*"
